export const COLORS = {
    BACKGROUND_COLOR: '#FEFFFF',
    TEXT_COLOR_BLACK: '#000000',
    TEXT_COLOR_WHITE: '#FFFFFF',
    BOX_COLOR_DARK: '#17252A',
    BOX_COLOR_LIGHT: '#3AAFA9',
    SECTION_COLOR: 'BFEA7C'
};
